In [1]:
import torch

In [13]:
num_entires = 5000
db = torch.rand(num_entires) > 0.5
db

tensor([False, False,  True,  ..., False, False,  True])

In [14]:
db.shape

torch.Size([5000])

In [15]:
db[0:5]

tensor([False, False,  True,  True, False])

In [17]:
db[0:2]

tensor([False, False])

In [18]:
db[3:]

tensor([ True, False,  True,  ..., False, False,  True])

In [19]:
torch.cat((db[0:2], db[3:]))

tensor([False, False,  True,  ..., False, False,  True])

In [20]:
remove_index = 2

In [27]:
def parralel_remove(db, remove_index):
    return torch.cat((db[0:remove_index], db[remove_index+1:]))

parralel_remove(db, 0)[0:5]

tensor([False,  True,  True, False,  True])

In [28]:
parralel_remove(db, 0).shape

torch.Size([4999])