In [2]:
import torch

In [4]:
num_entries = 5000

db = torch.randn(num_entries) > 0.5
db

tensor([False,  True, False,  ..., False, False, False])

In [5]:
db.shape

torch.Size([5000])

In [6]:
remove_index = 2

In [7]:
db[0:2]

tensor([False,  True])

In [8]:
db[3:]

tensor([ True, False,  True,  ..., False, False, False])

In [9]:
db[0:5]

tensor([False,  True, False,  True, False])

In [21]:
torch.cat((db[0:2], db[3:]))[0:5]

tensor([False,  True,  True, False,  True])

In [22]:
def get_parallel_db(db, remove_index):
  return torch.cat((db[0:remove_index], db[remove_index+1:]))

In [23]:
get_parallel_db(db, remove_index)

tensor([False,  True,  True,  ..., False, False, False])

In [24]:
def get_parallel_dbs(db):

  parallel_dbs = list()

  for i in range(len(db)):
    pdb = get_parallel_db(db, i)
    parallel_dbs.append(pdb)
  
  return parallel_dbs

In [25]:
pdbs = get_parallel_dbs(db)

In [26]:
pdbs

[tensor([ True, False,  True,  ..., False, False, False]),
 tensor([False, False,  True,  ..., False, False, False]),
 tensor([False,  True,  True,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]),
 tensor([False,  True, False,  ..., False, False, False]

In [27]:
def create_db_and_parallels(num_entries):

  db = torch.randn(num_entries) > 0.5
  pdb = get_parallel_dbs(db)

  return db, pdb

In [28]:
db, pdbs = create_db_and_parallels(20)

In [29]:
db

tensor([ True, False,  True,  True,  True, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False, False])

In [30]:
pdbs

[tensor([False,  True,  True,  True, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False]),
 tensor([ True,  True,  True,  True, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False]),
 tensor([ True, False,  True,  True, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False]),
 tensor([ True, False,  True,  True, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False]),
 tensor([ True, False,  True,  True, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False]),
 tensor([ True, False,  True,  True,  True, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False]),
 tensor([ True, False,  True,  True,  True, False, False,  True, False, False,
   

In [37]:
def query(db):
  return db.sum()

In [38]:
query(db)

tensor(5)

In [39]:
query(pdbs[6])

tensor(5)

In [40]:
full_db_result = query(db)

In [41]:
max_distance = 0

for pdb in pdbs:
  pdb_result = query(pdb)

  db_distance = torch.abs(pdb_result - full_db_result)

  if db_distance > max_distance:
    max_distance = db_distance

In [42]:
max_distance

tensor(1)